import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import type { ValidateFunction } from "ajv";
import type { JsonValue } from "../types.js";
import type {
  GeneratedContentProvenance,
  ProvenanceAdapterHook,
  ProvenanceAdapterHookContext,
  ProvenanceAdapterHookResult,
  ProvenanceFormat,
  ProvenanceReason,
  ProvenanceRedactionOptions,
  ProvenanceValidationResult
} from "./types.js";

const schemaDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../schemas");
const ajv = new Ajv2020({ allErrors: true, strict: false });
let provenanceValidator: ValidateFunction | undefined;
let adapterHookResultValidator: ValidateFunction | undefined;

const unsafeKeyPattern = /(?:raw[_-]?(?:prompt|content|provider|payload|trace|transcript)|provider[_-]?payload|private[_-]?diagnostic|secret|password|credential|api[_-]?key|access[_-]?token|private[_-]?key)/i;
const unsafeValuePattern = /(?:BEGIN PRIVATE KEY|sk-[A-Za-z0-9]{8,}|raw provider payload|raw_provider_payload|raw prompt|raw_prompt|private diagnostic|tenant_should_not_escape)/i;
const sourceTypesRequiringHash = new Set([
  "user_message",
  "uploaded_file",
  "retrieved_document",
  "tool_result",
  "external_api",
  "model_output"
]);

export function createGeneratedContentProvenance(
  input: Omit<GeneratedContentProvenance, "schemaVersion">
): GeneratedContentProvenance {
  return {
    ...input,
    approvalRefs: input.approvalRefs ? [...input.approvalRefs].sort() : undefined,
    capabilityRefs: [...input.capabilityRefs].sort(compareCapabilityRefs),
    modelRefs: [...new Set(input.modelRefs)].sort(),
    providerRefs: [...input.providerRefs].sort(compareProviderRefs),
    schemaVersion: "1.0",
    sourceRefs: [...input.sourceRefs].sort((left, right) => left.sourceId.localeCompare(right.sourceId))
  };
}

export function validateGeneratedContentProvenance(record: unknown): ProvenanceValidationResult {
  const schemaErrors = validateWithSchema(record, getProvenanceValidator());
  const semanticErrors = schemaErrors.length === 0
    ? semanticProvenanceErrors(record as GeneratedContentProvenance)
    : [];
  const markerErrors = unsafeMarkerFailures(record);
  const errors = [...schemaErrors, ...semanticErrors, ...markerErrors];

  return {
    errors,
    valid: errors.length === 0,
    warnings: []
  };
}

export function redactGeneratedContentProvenance(
  record: GeneratedContentProvenance,
  options: ProvenanceRedactionOptions = {}
): GeneratedContentProvenance {
  return {
    ...record,
    approvalRefs: record.approvalRefs ? [...record.approvalRefs] : undefined,
    capabilityRefs: record.capabilityRefs.map((capability) => ({ ...capability })),
    modelRefs: [...record.modelRefs],
    providerRefs: record.providerRefs.map((provider) => {
      const safeProvider = { ...provider };
      if (options.omitProviderRequestRefs) {
        delete safeProvider.requestId;
        delete safeProvider.responseId;
      }
      return safeProvider;
    }),
    sourceRefs: record.sourceRefs.map((source) => ({ ...source })),
    traceRef: options.omitTraceRef ? undefined : record.traceRef ? { ...record.traceRef } : undefined
  };
}

export function formatGeneratedContentProvenance(
  record: GeneratedContentProvenance,
  format: ProvenanceFormat = "json"
): string {
  if (format === "json") {
    return `${JSON.stringify(record, null, 2)}\n`;
  }

  const lines = [
    `# Generated Content Provenance: ${record.contentId}`,
    "",
    `Created: ${record.createdAt}`,
    `Content type: ${record.contentType}`,
    `Generated by: ${record.generatedBy}`,
    "",
    "## Providers",
    ...(record.providerRefs.length === 0
      ? ["- none"]
      : record.providerRefs.map((provider) => `- ${provider.providerId}${provider.runId ? ` run=${provider.runId}` : ""}`)),
    "",
    "## Models",
    ...(record.modelRefs.length === 0 ? ["- none"] : record.modelRefs.map((model) => `- ${model}`)),
    "",
    "## Capabilities",
    ...(record.capabilityRefs.length === 0
      ? ["- none"]
      : record.capabilityRefs.map((capability) => `- ${capability.capabilityId}${capability.operation ? ` (${capability.operation})` : ""}`)),
    "",
    "## Sources",
    ...record.sourceRefs.map((source) => `- ${source.sourceType}:${source.sourceId}${source.contentHash ? ` hash=${source.contentHash}` : ""}`),
    "",
    "Raw prompts, provider payloads, transcripts, secrets, and sensitive source content are not included.",
    ""
  ];

  return `${lines.join("\n")}`;
}

export async function runProvenanceAdapterHook(
  record: GeneratedContentProvenance,
  hook: ProvenanceAdapterHook,
  context: ProvenanceAdapterHookContext = {}
): Promise<ProvenanceAdapterHookResult> {
  const recordValidation = validateGeneratedContentProvenance(record);
  const adapterId = context.adapterId ?? "provenance_adapter";
  if (!recordValidation.valid) {
    return failedAdapterResult(adapterId, "provenance_record_invalid", "Generated content provenance failed validation before adapter handoff.");
  }

  try {
    const result = await hook(redactGeneratedContentProvenance(record), context);
    const resultValidation = validateAdapterHookResult(result);
    if (!resultValidation.valid) {
      return failedAdapterResult(adapterId, "provenance_adapter_result_invalid", "Provenance adapter hook returned unsafe or invalid metadata.");
    }
    return result;
  } catch {
    return failedAdapterResult(adapterId, "provenance_adapter_failed", "Provenance adapter hook failed.");
  }
}

export function hashProvenanceValue(value: unknown): string {
  return `sha256:${createHash("sha256").update(stableStringify(value)).digest("hex")}`;
}

function validateAdapterHookResult(result: unknown): ProvenanceValidationResult {
  const schemaErrors = validateWithSchema(result, getAdapterHookResultValidator());
  const markerErrors = unsafeMarkerFailures(result);
  const errors = [...schemaErrors, ...markerErrors];

  return {
    errors,
    valid: errors.length === 0,
    warnings: []
  };
}

function semanticProvenanceErrors(record: GeneratedContentProvenance): ProvenanceReason[] {
  const errors: ProvenanceReason[] = [];

  if (Number.isNaN(Date.parse(record.createdAt))) {
    errors.push(reason("provenance_created_at_invalid", "createdAt must be an ISO-like timestamp.", "/createdAt"));
  }

  if (record.providerRefs.length === 0) {
    errors.push(reason("provenance_provider_refs_required", "At least one provider reference is required.", "/providerRefs"));
  }

  if (record.modelRefs.length === 0) {
    errors.push(reason("provenance_model_refs_required", "At least one model reference is required.", "/modelRefs"));
  }

  if (record.capabilityRefs.length === 0) {
    errors.push(reason("provenance_capability_refs_required", "At least one capability reference is required.", "/capabilityRefs"));
  }

  if (record.sourceRefs.length === 0) {
    errors.push(reason("provenance_source_refs_required", "At least one source reference is required.", "/sourceRefs"));
  }

  for (const [index, source] of record.sourceRefs.entries()) {
    if (sourceTypesRequiringHash.has(source.sourceType) && !source.contentHash) {
      errors.push(reason(
        "provenance_source_hash_required",
        "Source references derived from content must include a contentHash instead of raw content.",
        `/sourceRefs/${index}/contentHash`
      ));
    }
  }

  return errors;
}

function validateWithSchema(value: unknown, validator: ValidateFunction): ProvenanceReason[] {
  if (validator(value)) {
    return [];
  }

  return (validator.errors ?? []).map((error) => reason(
    "provenance_schema_validation_failed",
    `${error.instancePath || "/"}: ${error.message ?? "schema validation failed"}`,
    error.instancePath || "/"
  ));
}

function unsafeMarkerFailures(value: unknown, pathName = ""): ProvenanceReason[] {
  const failures: ProvenanceReason[] = [];

  if (Array.isArray(value)) {
    for (const [index, item] of value.entries()) {
      failures.push(...unsafeMarkerFailures(item, `${pathName}/${index}`));
    }
    return failures;
  }

  if (value && typeof value === "object") {
    for (const [key, nested] of Object.entries(value as Record<string, unknown>)) {
      const nextPath = `${pathName}/${key}`;
      if (unsafeKeyPattern.test(key)) {
        failures.push(reason("provenance_unsafe_field", "Provenance metadata must not include raw content, payload, credential, or private diagnostic fields.", nextPath));
      }
      failures.push(...unsafeMarkerFailures(nested, nextPath));
    }
    return failures;
  }

  if (typeof value === "string" && unsafeValuePattern.test(value)) {
    failures.push(reason("provenance_unsafe_value", "Provenance metadata contains raw payload, credential, or private diagnostic-looking content.", pathName || "/"));
  }

  return failures;
}

function failedAdapterResult(adapterId: string, code: string, message: string): ProvenanceAdapterHookResult {
  return {
    adapterId,
    diagnostics: [reason(code, message)],
    schemaVersion: "1.0",
    status: "failed"
  };
}

function reason(code: string, message: string, pathName?: string): ProvenanceReason {
  return {
    code,
    message,
    path: pathName,
    severity: "error"
  };
}

function getProvenanceValidator(): ValidateFunction {
  provenanceValidator ??= ajv.compile(readSchema("provenance/generated-content-provenance.schema.json"));
  return provenanceValidator;
}

function getAdapterHookResultValidator(): ValidateFunction {
  adapterHookResultValidator ??= ajv.compile(readSchema("provenance/provenance-adapter-hook-result.schema.json"));
  return adapterHookResultValidator;
}

function readSchema(fileName: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path.join(schemaDirectory, fileName), "utf8")) as Record<string, unknown>;
}

function compareProviderRefs(left: GeneratedContentProvenance["providerRefs"][number], right: GeneratedContentProvenance["providerRefs"][number]): number {
  return `${left.providerId}:${left.runId ?? ""}:${left.responseId ?? ""}`.localeCompare(`${right.providerId}:${right.runId ?? ""}:${right.responseId ?? ""}`);
}

function compareCapabilityRefs(left: GeneratedContentProvenance["capabilityRefs"][number], right: GeneratedContentProvenance["capabilityRefs"][number]): number {
  return `${left.capabilityId}:${left.operation ?? ""}:${left.version ?? ""}`.localeCompare(`${right.capabilityId}:${right.operation ?? ""}:${right.version ?? ""}`);
}

function stableStringify(value: unknown): string {
  return JSON.stringify(sortValue(value));
}

function sortValue(value: unknown): JsonValue {
  if (Array.isArray(value)) {
    return value.map(sortValue);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, nested]) => [key, sortValue(nested)])
    );
  }

  if (typeof value === "bigint" || typeof value === "function" || typeof value === "symbol" || value === undefined) {
    return null;
  }

  return value as JsonValue;
}
